### ISSUE TITLE
The s3 secret shouldn't be in this example

### ISSUE THREAD

**Issue by TheYkk** [dagger/examples#19]
In this example, the s3 secret can be easily decrypted.

If the secret must remain in the project I think the secret authorization must be limited.

**Comment by shykes** [comment]
Thanks for reporting. Yes, this is normal. The S3 key is meant to be shared publicly so that anyone following the tutorial can easily deploy something to the shared bucket. We have carefully restricted privileges for these credentials to the absolute minimum.

Please let us know if you think we have missed something when reducing privileges! Thanks!

**Comment by samalba** [comment]
Closing this. If someone has a better idea to demo key sharing, feel free to re-open.
